### ISSUE TITLE
React-redux Kanban Board setup

### ISSUE THREAD

**Issue by Efiamotu-1** [Efiamotu-1/SpaceHub#25]
[link to github repo](https://github.com/Efiamotu-1/SpaceHub/issues)

Hi,

There are two members in this team @Efiamotu-1 & @cmolinan

**Comment by brytebee** [comment]
Hi Team👋,

##

### Highlights💡
- The number of team members is stated.✔️ 
- A link to the project is added.✔️
- The `Kanban board` is properly set up.✔️
- Task cards are fairly divided.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/3o6fIUZTTDl0IDjbZS/giphy.gif)

Good luck! 🎉 

##

###  **Optional Suggestions:**
- N/A

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by cmolinan** [comment]
Thanks !
